-- MySQL Script generated by MySQL Workbench
-- Fri Mar 24 22:00:10 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema controleProducao
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `controleProducao` ;

-- -----------------------------------------------------
-- Schema controleProducao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `controleProducao` DEFAULT CHARACTER SET utf8 ;
USE `controleProducao` ;

-- -----------------------------------------------------
-- Table `controleProducao`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleProducao`.`produto` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `lucro` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleProducao`.`formula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleProducao`.`formula` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `principal` TINYINT NOT NULL,
  `produto_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `produto_id`),
  INDEX `fk_formula_produto1_idx` (`produto_id` ASC) VISIBLE,
  CONSTRAINT `fk_formula_produto1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `controleProducao`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleProducao`.`origem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleProducao`.`origem` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleProducao`.`materiaPrima`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleProducao`.`materiaPrima` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `inci` VARCHAR(45) NOT NULL,
  `estoque` DOUBLE NOT NULL,
  `minimo` DOUBLE NOT NULL,
  `origem_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `origem_id`),
  INDEX `fk_materiaPrima_origem1_idx` (`origem_id` ASC) VISIBLE,
  CONSTRAINT `fk_materiaPrima_origem1`
    FOREIGN KEY (`origem_id`)
    REFERENCES `controleProducao`.`origem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleProducao`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleProducao`.`fornecedor` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `telefone` CHAR(17) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleProducao`.`materiaPrima_has_fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleProducao`.`materiaPrima_has_fornecedor` (
  `materiaPrima_id` INT UNSIGNED NOT NULL,
  `fornecedor_id` INT UNSIGNED NOT NULL,
  `preco` DOUBLE NOT NULL,
  PRIMARY KEY (`materiaPrima_id`, `fornecedor_id`),
  INDEX `fk_materiaPrima_has_fornecedor_fornecedor1_idx` (`fornecedor_id` ASC) VISIBLE,
  INDEX `fk_materiaPrima_has_fornecedor_materiaPrima_idx` (`materiaPrima_id` ASC) VISIBLE,
  CONSTRAINT `fk_materiaPrima_has_fornecedor_materiaPrima`
    FOREIGN KEY (`materiaPrima_id`)
    REFERENCES `controleProducao`.`materiaPrima` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materiaPrima_has_fornecedor_fornecedor1`
    FOREIGN KEY (`fornecedor_id`)
    REFERENCES `controleProducao`.`fornecedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleProducao`.`formula_has_materiaPrima`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleProducao`.`formula_has_materiaPrima` (
  `formula_id` INT UNSIGNED NOT NULL,
  `materiaPrima_id` INT UNSIGNED NOT NULL,
  `porcentagem` DOUBLE NOT NULL,
  `passo` SMALLINT(3) NOT NULL,
  PRIMARY KEY (`formula_id`, `materiaPrima_id`),
  INDEX `fk_formula_has_materiaPrima_materiaPrima1_idx` (`materiaPrima_id` ASC) VISIBLE,
  INDEX `fk_formula_has_materiaPrima_formula1_idx` (`formula_id` ASC) VISIBLE,
  CONSTRAINT `fk_formula_has_materiaPrima_formula1`
    FOREIGN KEY (`formula_id`)
    REFERENCES `controleProducao`.`formula` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_formula_has_materiaPrima_materiaPrima1`
    FOREIGN KEY (`materiaPrima_id`)
    REFERENCES `controleProducao`.`materiaPrima` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleProducao`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleProducao`.`usuario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `temPermissao` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleProducao`.`rotulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleProducao`.`rotulo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` TINYINT NOT NULL,
  `tamanho` VARCHAR(10) NOT NULL,
  `principal` TINYINT NOT NULL,
  `nome` VARCHAR(35) NULL,
  `produto_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `produto_id`),
  INDEX `fk_rotulo_produto1_idx` (`produto_id` ASC) VISIBLE,
  CONSTRAINT `fk_rotulo_produto1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `controleProducao`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleProducao`.`rotulo_has_fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleProducao`.`rotulo_has_fornecedor` (
  `rotulo_id` INT UNSIGNED NOT NULL,
  `fornecedor_id` INT UNSIGNED NOT NULL,
  `preco` DOUBLE NOT NULL,
  PRIMARY KEY (`rotulo_id`, `fornecedor_id`),
  INDEX `fk_rotulo_has_fornecedor_fornecedor1_idx` (`fornecedor_id` ASC) VISIBLE,
  INDEX `fk_rotulo_has_fornecedor_rotulo1_idx` (`rotulo_id` ASC) VISIBLE,
  CONSTRAINT `fk_rotulo_has_fornecedor_rotulo1`
    FOREIGN KEY (`rotulo_id`)
    REFERENCES `controleProducao`.`rotulo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rotulo_has_fornecedor_fornecedor1`
    FOREIGN KEY (`fornecedor_id`)
    REFERENCES `controleProducao`.`fornecedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleProducao`.`embalagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleProducao`.`embalagem` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `tipo` SMALLINT(5) NOT NULL,
  `tamanho` VARCHAR(15) NULL,
  `descricao` VARCHAR(60) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleProducao`.`embalagem_has_fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleProducao`.`embalagem_has_fornecedor` (
  `embalagem_id` INT UNSIGNED NOT NULL,
  `fornecedor_id` INT UNSIGNED NOT NULL,
  `preco` DOUBLE NOT NULL,
  PRIMARY KEY (`embalagem_id`, `fornecedor_id`),
  INDEX `fk_embalagem_has_fornecedor_fornecedor1_idx` (`fornecedor_id` ASC) VISIBLE,
  INDEX `fk_embalagem_has_fornecedor_embalagem1_idx` (`embalagem_id` ASC) VISIBLE,
  CONSTRAINT `fk_embalagem_has_fornecedor_embalagem1`
    FOREIGN KEY (`embalagem_id`)
    REFERENCES `controleProducao`.`embalagem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_embalagem_has_fornecedor_fornecedor1`
    FOREIGN KEY (`fornecedor_id`)
    REFERENCES `controleProducao`.`fornecedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controleProducao`.`produto_has_embalagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controleProducao`.`produto_has_embalagem` (
  `produto_id` INT UNSIGNED NOT NULL,
  `embalagem_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`produto_id`, `embalagem_id`),
  INDEX `fk_produto_has_embalagem_embalagem1_idx` (`embalagem_id` ASC) VISIBLE,
  INDEX `fk_produto_has_embalagem_produto1_idx` (`produto_id` ASC) VISIBLE,
  CONSTRAINT `fk_produto_has_embalagem_produto1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `controleProducao`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_has_embalagem_embalagem1`
    FOREIGN KEY (`embalagem_id`)
    REFERENCES `controleProducao`.`embalagem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
